Remove policy-specific mint guards and add GUARD_POLICY to `kip.token-policy-v2.concrete-policies` (#79)
* reset mint guard change

* remove mint-guards in all policies except guard-token-policy

* move guard policy to concrete-policy

* update readme

* emit events on guard-policy-v1.enforce-init

---------

Co-authored-by: ggobugi27 <ggobugi27@github.com>

diff --git a/.github/workflows/pact.yml b/.github/workflows/pact.yml
--- a/.github/workflows/pact.yml
+++ b/.github/workflows/pact.yml
@@ -72,3 +72,9 @@ jobs:
           cat out.log
           r=`tail -1 out.log | grep "Load successful"`
           if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
+      - name: Test concrete guard-policy
+        run: |
+          bin/pact -t pact/concrete-policies/guard-policy/guard-policy-v1.repl > out.log 2>&1
+          cat out.log
+          r=`tail -1 out.log | grep "Load successful"`
+          if [ -n "$r" ]; then exit 0; else echo "Pact run failed."; exit 1; fi
